"""Deterministic SIMULATED market data.

Purpose
-------
The system must be fully runnable, testable and demonstrable **without** a live
Upstox token, without hitting the broker, and without pretending that made-up
numbers are real market data.

Everything produced here is:

* **labelled as simulated** in the database (``source="synthetic"``) and in every
  API response (``data_source: "SIMULATED"``);
* **deterministic** for a given ``(symbol, date, seed)`` so backtests are
  reproducible;
* clearly separated from real data - the analytics layer tags results that used
  simulated data, and the dashboard shows a SIMULATED DATA banner.

It is generated by a realistic intraday model: an overnight gap, a session
trend with volatility clustering, a U-shaped intraday volume profile, and a
multi-day regime cycle. This is a development/CI fixture, NOT a price forecast
and NEVER a basis for a live trading decision.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import math
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

from ..timeutil import IST, market_open, now_ist
from ..broker.upstox_market_data import Candle

SIMULATED_SOURCE = "synthetic"
SIMULATED_FLAG = True

# A fixed, auditable (not pulled from any real feed) reference price per symbol.
# These are *fixtures*, not market data - the dashboard always labels them.
_DEFAULT_BASE_PRICE: Dict[str, float] = {
    "RELIANCE": 2600.0, "HDFCBANK": 1600.0, "ICICIBANK": 1100.0, "INFY": 1550.0,
    "TCS": 3900.0, "SBIN": 800.0, "BHARTIARTL": 1500.0, "ITC": 440.0,
    "LT": 3500.0, "KOTAKBANK": 1750.0, "AXISBANK": 1100.0, "HINDUNILVR": 2400.0,
    "BAJFINANCE": 7000.0, "MARUTI": 12000.0, "ASIANPAINT": 2900.0, "SUNPHARMA": 1500.0,
    "TITAN": 3400.0, "ULTRACEMCO": 11000.0, "TATAMOTORS": 950.0, "NESTLEIND": 2400.0,
    "NTPC": 380.0, "POWERGRID": 300.0, "WIPRO": 550.0, "ONGC": 250.0,
    "JSWSTEEL": 900.0, "TATASTEEL": 150.0, "HINDALCO": 650.0, "COALINDIA": 450.0,
    "M&M": 2800.0, "ADANIENT": 3000.0, "ADANIPORTS": 1400.0, "TECHM": 1600.0,
    "BAJAJFINSV": 1650.0, "GRASIM": 2500.0, "INDUSINDBK": 1000.0, "DRREDDY": 1200.0,
    "CIPLA": 1500.0, "DIVISLAB": 5800.0, "EICHERMOT": 4800.0, "HEROMOTOCO": 4500.0,
    "BRITANNIA": 5000.0, "APOLLOHOSP": 7000.0, "BAJAJ-AUTO": 9000.0, "HCLTECH": 1700.0,
    "SBILIFE": 1500.0, "HDFCLIFE": 700.0, "TATACONSUM": 1000.0, "SHRIRAMFIN": 3000.0,
    "TRENT": 6000.0, "BEL": 300.0,
}

DEFAULT_TICK = 0.05


def _seed(*parts: object) -> int:
    digest = hashlib.sha256("|".join(str(p) for p in parts).encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big", signed=False)


def base_price(symbol: str) -> float:
    if symbol in _DEFAULT_BASE_PRICE:
        return _DEFAULT_BASE_PRICE[symbol]
    # Stable pseudo-price derived from the symbol so runs are reproducible.
    return 100.0 + (_seed("price", symbol) % 4000) / 4.0


@dataclass
class SimulatedSession:
    symbol: str
    date: dt.date
    candles: List[Candle]
    regime: str
    gap_pct: float

    @property
    def open(self) -> float:
        return self.candles[0].open if self.candles else 0.0

    @property
    def close(self) -> float:
        return self.candles[-1].close if self.candles else 0.0

    @property
    def high(self) -> float:
        return max(c.high for c in self.candles) if self.candles else 0.0

    @property
    def low(self) -> float:
        return min(c.low for c in self.candles) if self.candles else 0.0


# NSE cash session: 09:15 -> 15:30 IST inclusive start times = 375 one-minute bars
SESSION_START_HOUR = 9
SESSION_START_MINUTE = 15
SESSION_MINUTES = 375


def session_timestamps(date: dt.date, minutes: int = SESSION_MINUTES) -> List[dt.datetime]:
    start = dt.datetime(date.year, date.month, date.day, SESSION_START_HOUR, SESSION_START_MINUTE, tzinfo=IST)
    return [start + dt.timedelta(minutes=i) for i in range(minutes)]


#: Deterministic regime model. A three-session "family" gives regimes realistic
#: persistence, while each individual session can still differ within the family.
_REGIME_DRIFT: Dict[str, float] = {
    "TREND_UP": 0.0030,
    "TREND_DOWN": -0.0030,
    "GAP_UP": 0.0018,
    "GAP_DOWN": -0.0018,
    "RANGE": 0.0000,
    "HIGH_VOLATILITY": 0.0000,
    "LOW_VOLATILITY": 0.0005,
    "EVENT_DRIVEN": 0.0000,
    "UNKNOWN": 0.0000,
}

_FAMILY_CHOICES: Dict[str, Tuple[Tuple[str, float], ...]] = {
    "bullish": (("TREND_UP", 0.55), ("TREND_UP", 0.15), ("GAP_UP", 0.12), ("RANGE", 0.18)),
    "bearish": (("TREND_DOWN", 0.55), ("TREND_DOWN", 0.15), ("GAP_DOWN", 0.12), ("RANGE", 0.18)),
    "neutral": (("RANGE", 0.60), ("LOW_VOLATILITY", 0.25), ("TREND_UP", 0.08), ("TREND_DOWN", 0.07)),
    "volatile": (("HIGH_VOLATILITY", 0.55), ("EVENT_DRIVEN", 0.20), ("TREND_DOWN", 0.13), ("TREND_UP", 0.12)),
}
_FAMILY_WEIGHTS: Tuple[Tuple[str, float], ...] = (
    ("bullish", 0.32),
    ("bearish", 0.28),
    ("neutral", 0.26),
    ("volatile", 0.14),
)


def _pick(weighted: Sequence[Tuple[str, float]], roll: float) -> str:
    total = sum(weight for _, weight in weighted)
    threshold = roll * total
    cumulative = 0.0
    for value, weight in weighted:
        cumulative += weight
        if threshold <= cumulative:
            return value
    return weighted[-1][0]


def _regime_for_date(date: dt.date, symbol: str) -> Tuple[str, float]:
    """Deterministic day-level regime and drift.

    Three-session families give persistence; the per-session roll adds variation.
    Everything is a pure function of the date (and symbol beta), so backtests are
    byte-for-byte reproducible.
    """
    block = date.toordinal() // 3
    family_roll = (_seed("regime-family", block) % 100_000) / 100_000.0
    family = _pick(_FAMILY_WEIGHTS, family_roll)

    day_roll = (_seed("regime-day", date.toordinal(), symbol) % 100_000) / 100_000.0
    regime = _pick(_FAMILY_CHOICES[family], day_roll)

    symbol_beta = 0.6 + (_seed("beta", symbol) % 90) / 100.0
    return regime, _REGIME_DRIFT[regime] * symbol_beta


def generate_session(
    symbol: str,
    date: dt.date,
    *,
    base: Optional[float] = None,
    interval_minutes: int = 1,
    volatility: float = 0.011,
    seed_salt: str = "",
) -> SimulatedSession:
    """Generate one deterministic simulated trading session."""
    base = base or base_price(symbol)
    rng = np.random.default_rng(_seed("session", symbol, date.isoformat(), seed_salt))

    regime, drift = _regime_for_date(date, symbol)
    vol = volatility * (1.6 if regime == "HIGH_VOLATILITY" else 0.6 if regime == "LOW_VOLATILITY" else 1.0)

    # Overnight gap
    gap_pct = float(rng.normal(0.0, 0.004))
    if regime == "TREND_UP":
        gap_pct += 0.0015
    elif regime == "TREND_DOWN":
        gap_pct -= 0.0015

    n = SESSION_MINUTES // interval_minutes
    step_vol = vol / math.sqrt(max(1, SESSION_MINUTES / max(1, interval_minutes)))

    # Ornstein-Uhlenbeck style mean reversion around the drift path, plus
    # volatility clustering via a slowly varying multiplier.
    clustering = np.ones(n)
    cluster = 1.0
    for i in range(n):
        cluster = 0.94 * cluster + 0.06 * float(rng.gamma(2.0, 0.5))
        clustering[i] = min(3.0, max(0.35, cluster))

    innovations = rng.normal(0.0, 1.0, n) * clustering * step_vol
    # Raw noise plus a per-bar drift increment. Noise is deliberately NOT
    # de-meaned: real sessions close away from their open.
    drift_path = np.full(n, drift / n)
    log_returns = drift_path + innovations

    open_price = base * (1.0 + gap_pct)
    closes = open_price * np.exp(np.cumsum(log_returns))

    # U-shaped volume profile (heavy open, heavy close)
    positions = np.linspace(0.0, 1.0, n)
    volume_profile = 0.45 + 1.5 * (np.exp(-positions * 6) + np.exp(-(1 - positions) * 6))
    base_volume = 150_000 + (_seed("vol", symbol) % 900_000)

    # Day-level activity shock: real sessions differ a lot in participation.
    # Lognormal keeps it strictly positive and gives a realistic long right tail.
    day_activity = float(np.exp(rng.normal(0.0, 0.42)))
    if regime in ("HIGH_VOLATILITY", "EVENT_DRIVEN"):
        day_activity *= 1.8
    elif regime == "LOW_VOLATILITY":
        day_activity *= 0.75
    day_activity = float(np.clip(day_activity, 0.35, 6.0))

    # Intraday bursts: a few minutes trade far above the local average, which is
    # exactly what a relative-volume breakout filter is designed to detect.
    burst = np.ones(n)
    for _ in range(int(rng.integers(2, 9))):
        centre = int(rng.integers(0, n))
        width = int(rng.integers(1, 7))
        magnitude = float(rng.uniform(1.5, 4.5))
        lo = max(0, centre - width)
        hi = min(n, centre + width)
        burst[lo:hi] = np.maximum(burst[lo:hi], rng.uniform(1.2, magnitude))

    timestamps = session_timestamps(date, SESSION_MINUTES)[::interval_minutes]
    candles: List[Candle] = []
    prev_close = open_price
    for i in range(n):
        close = float(closes[i])
        body_high = max(prev_close, close)
        body_low = min(prev_close, close)
        wick = abs(float(rng.normal(0.0, 1.0))) * step_vol * close * 0.9
        high = body_high + wick
        low = max(0.05, body_low - wick)
        move_intensity = 1.0 + 0.25 * abs(log_returns[i]) / max(step_vol, 1e-9)
        volume = float(
            base_volume
            * volume_profile[i]
            * day_activity
            * burst[i]
            * float(rng.uniform(0.65, 1.45))
            / max(1, SESSION_MINUTES / interval_minutes)
            * min(2.5, move_intensity)
        )
        candles.append(
            Candle(
                ts=timestamps[i],
                open=round(prev_close, 2),
                high=round(high, 2),
                low=round(low, 2),
                close=round(close, 2),
                volume=round(volume, 0),
                open_interest=0.0,
                instrument_key="",
                timeframe=f"{interval_minutes}m",
            )
        )
        prev_close = close

    return SimulatedSession(symbol=symbol, date=date, candles=candles, regime=regime, gap_pct=gap_pct)


def generate_history(
    symbol: str,
    start: dt.date,
    end: dt.date,
    *,
    interval_minutes: int = 1,
    include_weekends: bool = False,
    holidays: Optional[Iterable[dt.date]] = None,
) -> List[Candle]:
    """Continuous multi-day simulated history for backtesting without a token."""
    holidays = set(holidays or ())
    out: List[Candle] = []
    cursor = start
    one_day = dt.timedelta(days=1)
    while cursor <= end:
        if (include_weekends or cursor.weekday() < 5) and cursor not in holidays:
            session = generate_session(symbol, cursor, interval_minutes=interval_minutes)
            out.extend(session.candles)
        cursor += one_day
    return out


def generate_index_history(
    index_symbol: str,
    start: dt.date,
    end: dt.date,
    *,
    interval_minutes: int = 1,
) -> List[Candle]:
    """Simulated index series (NIFTY / India VIX) with index-like volatility."""
    is_vix = "VIX" in index_symbol.upper()
    base = 12.0 if is_vix else 22000.0
    vol = 0.02 if is_vix else 0.006
    return _index_series(index_symbol, start, end, base, vol, interval_minutes)


def _index_series(
    index_symbol: str, start: dt.date, end: dt.date, base: float, vol: float, interval_minutes: int
) -> List[Candle]:
    out: List[Candle] = []
    level = base
    cursor = start
    one_day = dt.timedelta(days=1)
    while cursor <= end:
        if cursor.weekday() < 5:
            rng = np.random.default_rng(_seed("index", index_symbol, cursor.isoformat()))
            regime, drift = _regime_for_date(cursor, f"__index__{index_symbol}")
            day_drift = drift * 1.4
            n = SESSION_MINUTES // interval_minutes
            step = vol / math.sqrt(max(1, SESSION_MINUTES / max(1, interval_minutes)))
            rets = rng.normal(day_drift / n, step, n)
            closes = level * np.exp(np.cumsum(rets))
            timestamps = session_timestamps(cursor, SESSION_MINUTES)[::interval_minutes]
            prev = level
            for i in range(n):
                close = float(closes[i])
                high = max(prev, close) * (1 + abs(float(rng.normal(0, step * 0.4))))
                low = min(prev, close) * (1 - abs(float(rng.normal(0, step * 0.4))))
                out.append(
                    Candle(
                        ts=timestamps[i],
                        open=round(prev, 2),
                        high=round(high, 2),
                        low=round(low, 2),
                        close=round(close, 2),
                        volume=0.0,
                        open_interest=0.0,
                        instrument_key=index_symbol,
                        timeframe=f"{interval_minutes}m",
                    )
                )
                prev = close
            level = float(closes[-1])
        cursor += one_day
    return out


def aggregate_candles(candles: Sequence[Candle], timeframe_minutes: int, label: str) -> List[Candle]:
    """Aggregate 1-minute candles into a higher timeframe.

    Only COMPLETE buckets are emitted, so a partially formed higher-timeframe
    candle can never leak into a backtest.
    """
    if timeframe_minutes <= 1:
        return list(candles)
    buckets: Dict[dt.datetime, List[Candle]] = {}
    for candle in candles:
        minutes_into_day = (candle.ts.hour * 60 + candle.ts.minute) - (SESSION_START_HOUR * 60 + SESSION_START_MINUTE)
        if minutes_into_day < 0:
            continue
        bucket_index = minutes_into_day // timeframe_minutes
        bucket_start = candle.ts - dt.timedelta(minutes=minutes_into_day % timeframe_minutes)
        buckets.setdefault(bucket_start, []).append(candle)

    out: List[Candle] = []
    for bucket_start in sorted(buckets):
        group = sorted(buckets[bucket_start], key=lambda c: c.ts)
        if len(group) < timeframe_minutes and timeframe_minutes <= 15:
            continue  # incomplete bucket (e.g. end of session) - skip
        out.append(
            Candle(
                ts=bucket_start,
                open=group[0].open,
                high=max(c.high for c in group),
                low=min(c.low for c in group),
                close=group[-1].close,
                volume=sum(c.volume for c in group),
                open_interest=group[-1].open_interest,
                instrument_key=group[0].instrument_key,
                timeframe=label,
            )
        )
    return out


__all__ = [
    "generate_session",
    "generate_history",
    "generate_index_history",
    "aggregate_candles",
    "session_timestamps",
    "base_price",
    "SimulatedSession",
    "SIMULATED_SOURCE",
    "SIMULATED_FLAG",
    "SESSION_START_HOUR",
    "SESSION_START_MINUTE",
    "SESSION_MINUTES",
]
